id: ADFA46064
title: .txt
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 23:40:32.421304
  last_modified_at: 2022-03-01 23:40:32.421312
